### ISSUE TITLE
下面是翻译结果，看起来效果不好，请问原因是？

### ISSUE THREAD

**Issue by Lix1993** [moon-hotel/TransformerTranslation#9]
下面是翻译结果

```
德语：Eine Gruppe von Menschen steht vor einem Iglu.
翻译： A group of people standing in front of an outdoor studio . 
英语：A group of people are facing an igloo.


德语：Ein Mann in einem blauen Hemd steht auf einer Leiter und putzt ein Fenster.
翻译： A man in a shirt standing on a ladder and cleaning a ladder . 
英语：A man in a blue shirt is standing on a ladder cleaning a window.
```

需要更多的train data吗？

**Comment by gzzyyxh** [comment]
你的batch size设置的多少？loss和acc是多少？学习率设置了吗，源代码里的学习率写的是0

**Comment by Lix1993** [comment]
@gzzyyxh 
lr是这里定义的：
[class CustomSchedule(object):](https://github.com/moon-hotel/TransformerTranslation/blob/b265526093d4c96fc859dde0c5cfebda94dd1563/train.py#L12)

其他默认，

![image](https://github.com/moon-hotel/TransformerTranslation/assets/12579295/0fce2178-efe8-436a-8f70-8bef402e9001)
我之前看到了最后一个epoch的loss和acc没有改善，以为训练可以结束了，
看起来还需要继续训练

**Comment by Lix1993** [comment]
![image](https://github.com/moon-hotel/TransformerTranslation/assets/12579295/e8990f65-6d0a-4e42-ab3f-e5776e2f7a73)

这次的效果好了很多

**Comment by Lix1993** [comment]
德语：Eine Gruppe von Menschen steht vor einem Iglu.
翻译： A group of people standing in front of an art truck . 
英语：A group of people are facing an igloo.


德语：Ein Mann in einem blauen Hemd steht auf einer Leiter und putzt ein Fenster.
翻译： A man in a blue shirt standing on a ladder cleaning a window . 
英语：A man in a blue shirt is standing on a ladder cleaning a window.

**Comment by Lix1993** [comment]
![image](https://github.com/moon-hotel/TransformerTranslation/assets/12579295/36ab0413-066e-40c4-80ab-152d991eb43c)
大概需要需要33epoch，每次10

**Comment by Lix1993** [comment]
德语：Eine Gruppe von Menschen steht vor einem Iglu.
翻译： A group of people standing in front of an igloo 
英语：A group of people are facing an igloo.


德语：Ein Mann in einem blauen Hemd steht auf einer Leiter und putzt ein Fenster.
翻译： A man wearing a blue shirt standing on a ladder cleaning a window . 
英语：A man in a blue shirt is standing on a ladder cleaning a window.

**Comment by gzzyyxh** [comment]
你有尝试增大batch size吗，我最大才72，train loss比你那图低5-10%，跑大的会莫名其妙退出

**Comment by Lix1993** [comment]
内存不够用吗？
